target_include_directories(carvera_sources PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")

add_subdirectory(accessories)
add_subdirectory(atc)
if(CANOPEN_SUPPORT)
    add_subdirectory(canopen)
endif()
add_subdirectory(drillingcycles)
add_subdirectory(endstops)
add_subdirectory(laser)
add_subdirectory(spindle)
add_subdirectory(switch)
add_subdirectory(temperaturecontrol)
add_subdirectory(temperatureswitch)
add_subdirectory(toolmanager)
add_subdirectory(zprobe)
